### ISSUE TITLE
Installation Error

### ISSUE THREAD

**Issue by mumbaigirl** [TridotsTech/Go1-Commerce#1]
Installing go1_commerce...
An error occurred while installing go1_commerce: ('Module Def', 'Accounts', IntegrityError(1062, "Duplicate entry 'Accounts' for key 'PRIMARY'"))
Traceback with variables (most recent call last):
  File "apps/frappe/frappe/commands/site.py", line 452, in install_app
    _install_app(app, verbose=context.verbose, force=force)
      context = {'sites': ['mysite.in'], 'force': False, 'verbose': False, 'profile': False}
      apps = ('go1_commerce',)
      force = False
      _install_app = <function install_app at 0x7f06be60a4d0>
      filelock = <function filelock at 0x7f06be6084c0>
      exit_code = 0
      site = 'mysite.in'
      app = 'go1_commerce'
      err = DuplicateEntryError('Module Def', 'Accounts', IntegrityError(1062, "Duplicate entry 'Accounts' for key 'PRIMARY'"))
  File "apps/frappe/frappe/installer.py", line 310, in install_app
    add_module_defs(name, ignore_if_duplicate=force)
      name = 'go1_commerce'
      verbose = False
      set_as_patched = True
      force = False
      sync_jobs = <function sync_jobs at 0x7f06bdb25360>
      sync_for = <function sync_for at 0x7f06bdb25e10>
      sync_customizations = <function sync_customizations at 0x7f06bf75b370>
      sync_fixtures = <function sync_fixtures at 0x7f06bdb26050>
      app_hooks = {'after_install': ['go1_commerce.go1_commerce.after_install.after_install'], 'app_description': ['Go1 Commerce is an Open Source eCommerce portal built on frappe framework.'], 'app_email': ['info@tridotstech.com'], 'app_include_css': ['/assets/go1_commerce/css/console.css', '/assets/go1_commerce/css/ui/uploader.css'], 'app_include_js': ['/assets/go1_commerce/js/ui/dialog_popup.js', '/assets/go1_commerce/js/default_methods.js', '/assets/go1_commerce/js/option.js', '/assets/go1_commerce/js/console.js', '/assets/go1_commerce/js/getting_started.js', 'assets/go1_commerce/js/ui/product_func_class.js', 'assets/go1_commerce/js/quick_entry/return_quick_entry.js'], 'app_license': ['mit'], 'app_logo_url': ['/assets/go1_commerce/images/go1_commerce_logo.svg'], 'app_name': ['go1_commerce'], 'app_publisher': ['Tridotstech PVT LTD'], 'app_title': ['Go1 Commerce'], 'auto_cancel_exempted_doctypes': ['Order'], 'boot_session': ['go1_commerce.go1_commerce.v2.common.boot_session'], 'default_roles': [{'role...
      installed_apps = ['frappe', 'erpnext', 'payments', 'ecommerce_integrations', 'print_designer', 'hrms', 'wiki', 'tldraw_whiteboard', 'india_compliance', 'webshop', 'insights', 'builder']
      app = 'builder'
      required_app = 'builder'
  File "apps/frappe/frappe/installer.py", line 650, in add_module_defs
    d.insert(ignore_permissions=True, ignore_if_duplicate=ignore_if_duplicate)
      app = 'go1_commerce'
      ignore_if_duplicate = False
      modules = ['Go1 Commerce', 'Accounts']
      module = 'Accounts'
      d = <ModuleDef: Accounts>
  File "apps/frappe/frappe/model/document.py", line 302, in insert
    self.db_insert(ignore_if_duplicate=ignore_if_duplicate)
      self = <ModuleDef: Accounts>
      ignore_permissions = True
      ignore_links = None
      ignore_if_duplicate = False
      ignore_mandatory = None
      set_name = None
      set_child_names = True
  File "apps/frappe/frappe/model/base_document.py", line 581, in db_insert
    raise frappe.DuplicateEntryError(self.doctype, self.name, e)
      self = <ModuleDef: Accounts>
      ignore_if_duplicate = False
      conflict_handler = ''
      d = {'name': 'Accounts', 'creation': '2024-10-11 14:39:51.250094', 'modified': '2024-10-11 14:39:51.250094', 'modified_by': 'Administrator', 'owner': 'Administrator', 'docstatus': 0, 'idx': 0, 'module_name': 'Accounts', 'custom': 0, 'package': None, 'app_name': 'go1_commerce', 'restrict_to_domain': None, '_user_tags': None, '_comments': None, '_assign': None, '_liked_by': None}
      columns = ['name', 'creation', 'modified', 'modified_by', 'owner', 'docstatus', 'idx', 'module_name', 'custom', 'package', 'app_name', 'restrict_to_domain', '_user_tags', '_comments', '_assign', '_liked_by']
frappe.exceptions.DuplicateEntryError: ('Module Def', 'Accounts', IntegrityError(1062, "Duplicate entry 'Accounts' for key 'PRIMARY'"))

Frappe Builder: v1.x.x-develop () (develop)

Ecommerce Integrations: v1.20.1 (main)

ERPNext: v15.38.1 (version-15)

Frappe Framework: v15.44.1 (version-15)

**Comment by TridotsTech** [comment]
hi, go1_commerce app is an independent ecommerce portal app which was built using frappe builder. This app dont need erpnext ,this requires frappe,builder apps only.

**Comment by mumbaigirl** [comment]
> hi, go1_commerce app is an independent ecommerce portal app which was built using frappe builder. This app dont need erpnext ,this requires frappe,builder apps only.

Yes, I know. When I tried to install it `bench --site mydomain.in install-app go1_commerce` it throws the above error
The error traceback indicates that there was an issue with the Frappe framework related to the "Accounts Settings"

**Comment by mumbaigirl** [comment]
> hi, go1_commerce app is an independent ecommerce portal app which was built using frappe builder. This app dont need erpnext ,this requires frappe,builder apps only.

Traceback (most recent call last):
  File "/usr/lib/python3.10/runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib/python3.10/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/home/user55/frappe-bench/apps/frappe/frappe/utils/bench_helper.py", line 114, in <module>
    main()
  File "/home/user55/frappe-bench/apps/frappe/frappe/utils/bench_helper.py", line 20, in main
    click.Group(commands=commands)(prog_name="bench")
  File "/home/user55/frappe-bench/env/lib/python3.10/site-packages/click/core.py", line 1157, in __call__
    return self.main(*args, **kwargs)
  File "/home/user55/frappe-bench/env/lib/python3.10/site-packages/click/core.py", line 1078, in main
    rv = self.invoke(ctx)
  File "/home/user55/frappe-bench/env/lib/python3.10/site-packages/click/core.py", line 1688, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/user55/frappe-bench/env/lib/python3.10/site-packages/click/core.py", line 1688, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/user55/frappe-bench/env/lib/python3.10/site-packages/click/core.py", line 1434, in invoke
    return method_object(*args, **kwargs)
  File "/home/user55/frappe-bench/apps/frappe/frappe/commands/__init__.py", line 29, in _func
    ret = f(frappe._dict(ctx.obj), *args, **kwargs)
  File "/home/user55/frappe-bench/apps/frappe/frappe/commands/site.py", line 660, in migrate
    SiteMigration(
  File "/home/user55/frappe-bench/apps/frappe/frappe/migrate.py", line 186, in run
    self.run_schema_updates()
  File "/home/user55/frappe-bench/apps/frappe/frappe/migrate.py", line 52, in wrapper
    raise e
  File "/home/user55/frappe-bench/apps/frappe/frappe/migrate.py", line 44, in wrapper
    ret = method(*args, **kwargs)
  File "/home/user55/frappe-bench/apps/frappe/frappe/migrate.py", line 120, in run_schema_updates
    frappe.model.sync.sync_all()
  File "/home/user55/frappe-bench/apps/frappe/frappe/model/sync.py", line 43, in sync_all
    sync_for(app, force, reset_permissions=reset_permissions)
  File "/home/user55/frappe-bench/apps/frappe/frappe/model/sync.py", line 111, in sync_for
    import_file_by_path(
  File "/home/user55/frappe-bench/apps/frappe/frappe/modules/import_file.py", line 146, in import_file_by_path
    import_doc(
  File "/home/user55/frappe-bench/apps/frappe/frappe/modules/import_file.py", line 239, in import_doc
    doc.insert()
  File "/home/user55/frappe-bench/apps/frappe/frappe/model/document.py", line 315, in insert
    self.run_post_save_methods()
  File "/home/user55/frappe-bench/apps/frappe/frappe/model/document.py", line 1128, in run_post_save_methods
    self.run_method("on_update")
  File "/home/user55/frappe-bench/apps/frappe/frappe/model/document.py", line 962, in run_method
    out = Document.hook(fn)(self, *args, **kwargs)
  File "/home/user55/frappe-bench/apps/frappe/frappe/model/document.py", line 1322, in composer
    return composed(self, method, *args, **kwargs)
  File "/home/user55/frappe-bench/apps/frappe/frappe/model/document.py", line 1304, in runner
    add_to_return_value(self, fn(self, *args, **kwargs))
  File "/home/user55/frappe-bench/apps/frappe/frappe/model/document.py", line 959, in fn
    return method_object(*args, **kwargs)
  File "/home/user55/frappe-bench/apps/frappe/frappe/core/doctype/doctype/doctype.py", line 531, in on_update
    self.run_module_method("on_doctype_update")
  File "/home/user55/frappe-bench/apps/frappe/frappe/core/doctype/doctype/doctype.py", line 629, in run_module_method
    module = load_doctype_module(self.name, self.module)
  File "/home/user55/frappe-bench/apps/frappe/frappe/modules/utils.py", line 258, in load_doctype_module
    raise ImportError(msg) from e
ImportError: Module import failed for Promotional Scheme, the DocType you're trying to open might be deleted.
Error: No module named 'go1_commerce.accounts.doctype.promotional_scheme'

**Comment by mumbaigirl** [comment]
> hi, go1_commerce app is an independent ecommerce portal app which was built using frappe builder. This app dont need erpnext ,this requires frappe,builder apps only.

Do you mean If I have Erpnext running on my frappe instance, does that mean I can't install Go 1 Commerce on the same instance? There doesn't seems to be enough information in your readme files , all of them are empty.

**Comment by TridotsTech** [comment]
> > hi, go1_commerce app is an independent ecommerce portal app which was built using frappe builder. This app dont need erpnext ,this requires frappe,builder apps only.
> 
> Do you mean If I have Erpnext running on my frappe instance, does that mean I can't install Go 1 Commerce on the same instance? There doesn't seems to be enough information in your readme files , all of them are empty.

Yes, You can try to install without erpnext. Please make sure builder app installed before installing go1 commere app.

**Comment by mumbaigirl** [comment]
> > > hi, go1_commerce app is an independent ecommerce portal app which was built using frappe builder. This app dont need erpnext ,this requires frappe,builder apps only.
> > 
> > 
> > Do you mean If I have Erpnext running on my frappe instance, does that mean I can't install Go 1 Commerce on the same instance? There doesn't seems to be enough information in your readme files , all of them are empty.
> 
> Yes, You can try to install without erpnext. Please make sure builder app installed before installing go1 commere app.

@TridotsTech I am currently facing a challenge , as my ERPNext instance is in production and uninstalling it won't be a good idea.  While creating a new instance could serve as a workaround, it would still lack integration. Moreover, establishing another bench would redirect the web to a new subdomain and require significant adjustments to the Nginx configuration, potentially leading to conflicts and complicating the process of multiple bench updates and SEO problems.

The native webshop app presents several issues: it is an unattended repository with numerous bugs and a subpar user interface. Furthermore, the native webshop introduces friction in the B2C order process, lacking a one-click checkout option. Instead, it places an order and subsequently prompts the customer to complete the purchase, which can deter sales. Additionally, the native webshop has limited payment gateway options, and product attributes and variants are fraught with bugs. It is concerning that such an important app has been overlooked by the Frappe team.

In contrast, Go 1 Commerce appears to be more intuitive and user-friendly. Unfortunately, I am unable to use it in production. I would prefer to install it on top of my existing bench with ERPNext, as this would enhance the user experience and create a more **cohesive native app environment.**

I would greatly appreciate it if you could ask your technical team to consider making Go 1 Commerce compatible with ERPNext v15 on the same bench.

Thank you, waiting for your reply.

**Comment by TridotsTech** [comment]
Hello @mumbaigirl ,

Its an independent e-commerce application with the power of Frappe framework and Frappe Builder, designed for those looking to build online stores without relying on ERPNext. This standalone solution offers flexibility and customization options. 

While we're currently focused on the independent version, we're actively working on integrating it with ERPNext. We'll provide updates on this integration progress soon. 

For those seeking an e-commerce solution built directly on ERPNext and Frappe, we recommend Go1Webshop. We understand that some users have encountered challenges with Frappe Webshop. We will try to address the mentioned issues with some alternate solutions and will keep you posted on this issue. 

Thank you for your valuable feedback. We'll keep you informed about our progress.

**Comment by princessfrombabylon99** [comment]
+1

**Comment by thatphythonguy** [comment]
+1
